baseURL = "https://www.xinrengui.com"
languageCode = "zh-CN"
title = "辛壬癸博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "xinrengui"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "admin"

[params]
  author = "admin"
  subtitle = "年年岁岁花相似，岁岁年年人不同。"
  keywords = "golang,go语言,java,博客,周易,八字,天干,地支"
  description = "专注于互联网，包括但不限于Go语言(golang)、Java,博客,周易,八字,天干,地支等"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = ""
  name = ""
  url = ""


## 侧边栏广告位


## 配置 utteranc评论,教程参考 https://utteranc.es/


## 开启版权声明，协议名字和链接都可以换


## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
